cleanerbot/ansible-security

- Docker/Dockerfile
- script/test_ansible.bats
```ansible all -m ping --ask-pass```
> add test for ansible ping to loopback interface

- dockerfiles/dockerfile-ansible
- dockerfiles/dockerfile-gocdserver
- script/test_ansible.bats
> Gocd docker

- Makefile
- circle.yml
- dockerfiles/dockerfile-ansible
- script/test_ansible.bats
@jumanjiman 
Conversion from Centos:7 to Alpine:3.3 beginning here :)
> begin conversion from centos:7 to alpine:3.3

- Makefile
- dockerfiles/dockerfile-ansible
- script/build
- script/clean
- script/options.bash
- script/test
- script/test_ansible.bats
* use consistent image name/tag between build and test
* bump ansible version to resolve https://github.com/cleanerbot/ansible-security/issues/16
> upgrade ansible from 1.9 to 2.0

- circle.yml
- script/build
- script/clean
- script/options.bash
- script/publish
- script/test
- script/test_ansible.bats
Resolves https://github.com/cleanerbot/ansible-security/issues/18
I split into multiple commits for granularity.
> use vars to separate local vs published image name/tag

- fixtures/Dockerfile
- script/test_ansible.bats
seems to be working
ubuntu@box64:~$ docker run --volumes-from playbooks-data -t -i --entrypoint bash ansible-security
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
bash-4.3# ls
bash-4.3# ls /etc/ansible/
inventory      test_playbook
> copy in fixtures directory

- dockerfiles/dockerfile-autostager
- playbook_examples/firewall_rule.j2
@jfach
Starter PR for dockerfile-autostager
> add shell dockerfile for #28

- dockerfiles/dockerfile-autostager
- script/build
- script/test_ansible.bats
@Jfach 
had a few minutes to start this.
> Autostager

- dockerfiles/dockerfile-autostager
before this commit: we used pip to install autostager
after this commit: we use git clone to install autostager
> dockerfile-autostager: install autostager via git

- webserver/server.py
just committing the initial model for the webserver. We can flesh out the model tomorrow.
> commit initial python webserver model to replace captain hook

- webserver/server.py
info: based off of expected data from client script
> webserver: updated initial server model

- dockerfiles/dockerfile-ansible
used `COPY /webserver /opt/ansible/webserver`
> dockerfile-ansible: copy webserver to image

- circle.yml
- script/clean
Get more information returned int the script clean step for circlci
> ansible-security: add cleanupdocker script to step

- webserver/server.py
> Webserver: self.respond instead of self.response(200)

- .editorconfig
- .gitattributes
- Makefile
- check.py
- helpful_files/play.py
- test/unit/fixture.py
- test/unit/pep8_tests.py
- webserver/server.py
I'd like to submit some code to the repo, but
the current mixed whitespace and indentation makes it
hard to understand the intent of the code.
Therefore let's first use PEP8 to enforce consistent code style, such as whitespace.
Resolves https://github.com/cleanerbot/ansible-security/issues/62
> use pep8 to improve code readability

- webserver/server.py
Fix indentation to resolve cleanerbot/ansible-security/issues/98.
> webserver: break up request handler into methods for clarity

- webserver/server.py
@jumanjiman 
thanks for the help with PR #102 
This one just fixes the parentheses.
> add self.play() and self.run() parentheses for add'l cleanup

- fixtures/Dockerfile
- helpful_files/build_autostager.sh
- helpful_files/build_controller.sh
- helpful_files/env_vars
- helpful_files/play.py
- script/build
- script/options.bash
- script/test_ansible.bats
> tests: add check for playbook execution

- circle.yml
> flake8: downgrade the version in use #116

- circle.yml
http://jorisroovers.github.io/gitlint/
> wip: trying out gitlint for linting commits

- dockerfiles/dockerfile-client
- script/test_gitlint.bats
work on conformity checker test.
```
ubuntu@box543:~/ansible-security$ gitlint
1: T5 Title contains the word 'WIP' (case-insensitive): "wip: testing out gitlint output"
3: B6 Body message is missing
ubuntu@box543:~/ansible-security$
```
> wip: testing out gitlint output
